# Generated by Django 5.0.4 on 2024-05-01 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_amount', models.IntegerField(default=1)),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate_item.estimateitem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.material')),
            ],
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='estimate_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimate_item.estimateitemtype'),
        ),
    ]
